// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./runtime.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
}
