name: typescript-library
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Clone
      run: |
        pipx run cookiecutter --no-input ./typescript-library 'project_description=github test'
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Test
      run: |
        set -euxo pipefail
        pushd github-test
        # New project setup
        npm install
        
        # Test other npm commands
        npm run test
        npm run format
        npm run lint
        npm run type-check
        npm run build
        
        # Test using it as a library
        popd
        cd ./typescript-library/test
        npm install
        npm run test

